// runtimes/opencode.mjs
export const id = 'opencode'

// opencode discovers skills through config.skills.paths. Pushing the plugin's
// own skills directory there is the whole integration: the runtime has native
// skill support, so parsing SKILL.md here would re-implement a feature the
// host already has.
const PLUGIN = `// Generated by vibekit. Do not edit.
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const SKILLS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../skills')

export const VibekitPlugin = async () => ({
  config: async config => {
    config.skills ??= {}
    config.skills.paths ??= []
    if (!config.skills.paths.includes(SKILLS)) config.skills.paths.push(SKILLS)
  },
})
`

function installDoc(config) {
  return [
    `# Installing ${config.name} for opencode`,
    '',
    '## Local checkout',
    '',
    'Add a local checkout to the `plugin` array in your `opencode.json`:',
    '',
    '```json',
    '{',
    `  "plugin": ["/path/to/local/${config.name}"]`,
    '}',
    '```',
    '',
    `Replace \`/path/to/local/${config.name}\` with the absolute path to your checkout.`,
    '',
    '## Git repository',
    '',
    `This form is available once ${config.name} is published to the repository's default branch:`,
    '',
    '```json',
    '{',
    `  "plugin": ["${config.name}@git+${config.repository}.git"]`,
    '}',
    '```',
    '',
    'Restart opencode. Verify with:',
    '',
    '```',
    'opencode debug skill',
    '```',
    '',
    'Each runtime installs separately; installing here does not affect any other.',
    '',
  ].join('\n')
}

export function emit(model) {
  return {
    '.opencode/plugins/vibekit.js': PLUGIN,
    '.opencode/INSTALL.md': installDoc(model.config),
  }
}

export function pkg() {
  return { main: './.opencode/plugins/vibekit.js' }
}

export function ships() {
  return ['.opencode/']
}
