// runtimes/opencode.mjs
export const id = 'opencode'

// opencode v2 takes skills one at a time through skill.transform, each with
// its name and description as separate fields. Both are baked in from the
// model, so the only frontmatter parser stays the generator's and the plugin
// reads each file for its content alone.
function plugin(model) {
  const list = model.skills
    .map(skill => `  ${JSON.stringify({ name: skill.name, description: skill.description })},`)
    .join('\n')
  return `// Generated by vibekit. Do not edit.
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const SKILLS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../skills')
const LIST = [
${list}
]

export default {
  id: ${JSON.stringify(model.config.name)},
  setup: async ctx => {
    await ctx.skill.transform(draft => {
      for (const { name, description } of LIST) {
        const file = path.join(SKILLS, name, 'SKILL.md')
        const content = readFileSync(file, 'utf8').replace(/^---\\r?\\n[\\s\\S]*?\\r?\\n---(?:\\r?\\n)?/, '')
        draft.add({ id: name, name, description, path: file, content })
      }
    })
  },
}
`
}

function installDoc(config) {
  return [
    `# Installing ${config.name} for opencode`,
    '',
    'Requires opencode v2.',
    '',
    '## Local checkout',
    '',
    'opencode v2 reads the skills directory of a local checkout directly. Add it to the `skills` array in your `opencode.json`:',
    '',
    '```json',
    '{',
    `  "skills": ["/path/to/local/${config.name}/skills"]`,
    '}',
    '```',
    '',
    `Replace \`/path/to/local/${config.name}\` with the absolute path to your checkout. With this route the skills are listed by \`opencode api skill.list\`, and \`opencode plugin list\` has no ${config.name} row.`,
    '',
    '## Git repository',
    '',
    `This form is available once ${config.name} is published to the repository's default branch:`,
    '',
    '```json',
    '{',
    `  "plugin": ["${config.name}@git+${config.repository}.git"]`,
    '}',
    '```',
    '',
    '## Verify',
    '',
    'Run `opencode reload`, then:',
    '',
    '```',
    'opencode plugin list',
    '```',
    '',
    `The list has a row whose ID is \`${config.name}\`.`,
    '',
    'That row shows opencode found the plugin. It stays when the plugin then failed to register its skills, so check those too. From your project directory:',
    '',
    '```',
    `opencode api skill.list -H "x-opencode-directory:$PWD" | grep -c '"id":"${config.bootstrap}"'`,
    '```',
    '',
    'It prints `1` when the skills are registered and `0` when they are not. This check also works for a local checkout added through the `skills` array.',
    '',
    `If you already have a skill with the same name as a ${config.name} skill, opencode uses yours and drops the ${config.name} one without a warning. The ${config.name} skill names are common words such as \`plan\`, \`debug\` and \`verify\`, so check for a clash.`,
    '',
    'Each runtime installs separately; installing here does not affect any other.',
    '',
  ].join('\n')
}

export function emit(model) {
  return {
    '.opencode/plugins/vibekit.js': plugin(model),
    '.opencode/INSTALL.md': installDoc(model.config),
  }
}

export function pkg() {
  return { main: './.opencode/plugins/vibekit.js' }
}

export function ships() {
  return ['.opencode/']
}
