// Generated by vibekit. Do not edit.
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const SKILLS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../skills')
const LIST = [
  {"name":"brainstorm","description":"Use before any creative or implementation work: features, components, behavior changes. Hard gate, no code before an approved design."},
  {"name":"debug","description":"Use when a check fails: a red test, a broken build, a failed clause, or a bug you can point at. Finds a root cause and gets it refuted before anything is fixed. Diagnosis is the product. This skill never edits."},
  {"name":"exec","description":"Use when a plan is approved and implementation has not started: dispatches one fresh subagent per task, runs each task's verify clause, and routes failures back instead of repairing them. One task, one commit."},
  {"name":"lazy","description":"Use at the start of any coding work: writing, adding, refactoring, fixing, designing. The laziness ladder, stdlib and native features before new code, one line before fifty. Stays on after."},
  {"name":"plain","description":"Use before writing any text, in chat or into a file. Thirteen rules that hold in every string you emit, including code comments, commit messages, PR bodies and docs. No em dash, no semicolon, no hard wrapping inside a paragraph, no curly quotes, no decorative emoji, no title case in headings, no bold label lists, no heading echo, no fragment runs, no padded triads, no rejected straw options, no unraised objections, no writing about the previous version. Stays on after."},
  {"name":"plan","description":"Use when a spec is approved and implementation has not started: turns it into a task-by-task plan with exact paths and checkable verification. No code here."},
  {"name":"quick","description":"Use when the user types /vibekit:quick: writes the change immediately under lazy's ladder, no spec, no plan, no subagents. Reports what it skipped."},
  {"name":"terse","description":"Use at the start of every session. Compress narration, never artifacts. Questions, evidence, specs, plans and warnings stay verbatim. Stays on after."},
  {"name":"using-vibekit","description":"Use when starting any conversation: establishes the auto-trigger discipline so guardrail skills fire instead of being silently skipped."},
  {"name":"verify","description":"Use before claiming a change is done, fixed or passing: checks the whole change against its spec, runs the checks no single task could, hunts for the bugs the change produced, and returns ready or not ready. Evidence or it did not happen."},
  {"name":"vibe","description":"Run a short intent through the pipeline. Invoked as /vibekit:vibe. Hands off to brainstorm and does nothing else."},
]

export default {
  id: "vibekit",
  setup: async ctx => {
    await ctx.skill.transform(draft => {
      for (const { name, description } of LIST) {
        const file = path.join(SKILLS, name, 'SKILL.md')
        const content = readFileSync(file, 'utf8').replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n)?/, '')
        draft.add({ id: name, name, description, path: file, content })
      }
    })
  },
}
