// Generated by vibekit. Do not edit.
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const SKILLS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../skills')

export const VibekitPlugin = async () => ({
  config: async config => {
    config.skills ??= {}
    config.skills.paths ??= []
    if (!config.skills.paths.includes(SKILLS)) config.skills.paths.push(SKILLS)
  },
})
